# Generated by Django 5.1.4 on 2024-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
